df<-read.table("../household_power_consumption.txt",header = T, sep = ";",stringsAsFactors = F)
df[,1]<-as.Date(df[,1],"%d/%m/%Y")
dfs<-subset(df,Date<="2007-2-2" & Date>="2007-2-1")
par(mfrow = c(1, 1))
dates<-as.POSIXct(paste(dfs$Date, dfs$Time), format="%Y-%m-%d %H:%M:%S")
plot(dates,as.numeric(dfs[,7]),xlab="",ylab = "Energy sub metering",type="l")
lines(dates,as.numeric(dfs[,8]),col="red")
lines(dates,as.numeric(dfs[,9]),col="blue")
legend("topright", lwd = 1, col = c("black", "red","blue"), legend =c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()